name: 🐛 Bug Report (with Logs)
description: Report audio dropouts, glitches, or connection issues.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🛑 STOP! READ THIS FIRST.
        We cannot fix audio glitches without seeing what the driver is doing.
        **"It no worky!" will be closed immediately.**
        
        ### 🚫 NO SIGNING ISSUES (macOS)
        If your error is "Signature invalid", "System Extension Blocked", or "Unidentified Developer":
        **DO NOT OPEN AN ISSUE.**
        * This is your local environment.
        * Read the README for troubleshooting.
        * Still no worky? Ask Apple.
        
        ### ⚡️ How to get your logs:
        
        **🍏 macOS Users:**
        1. Download the driver folder.
        2. Double-click **`debug_logs.command`**.
        3. Wait for it to dump history, then reproduce your glitch.
        4. A text file will appear on your Desktop. Attach it below.
        
        **🐧 Linux Users:**
        1. Run `dmesg -w` in a terminal.
        2. Plug in the device and reproduce the glitch.
        3. Copy the output relevant to USB/Audio into a text file.
        4. Attach it below.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-Submission Checklist
      options:
        - label: I confirm this is NOT a code signing / certificate error.
          required: true
        - label: I have attached the log file (required for bug reports).
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Describe the Bug
      description: What happened? Did audio stop? Did it crackle?
      placeholder: "I was playing a track in Traktor and..."
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Device Model
      options:
        - Allen & Heath Xone:DB4
        - Allen & Heath Xone:DB2
        - Allen & Heath Xone:DX
        - Allen & Heath Xone:4D
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - macOS 12 (Monterey)
        - macOS 11 (Big Sur)
        - macOS 10.15 (Catalina)
        - Linux (Ubuntu/Debian)
        - Linux (Arch/Manjaro)
        - Linux (Fedora)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 📎 Attach Debug Log (REQUIRED)
      description: |
        **macOS:** Drag and drop the `.txt` file generated by the script.
        **Linux:** Paste your `dmesg` / `journalctl` output or attach a file.
      placeholder: "Drag & Drop Ploytec_Debug_Log...txt here"
    validations:
      required: true