#ifndef PloytecDriverKeys_h
#define PloytecDriverKeys_h

enum PloytecDriverExternalMethod
{
	PloytecDriverExternalMethod_Open,
	PloytecDriverExternalMethod_Close,
	PloytecDriverExternalMethod_GetFirmwareVer,
	PloytecDriverExternalMethod_GetDeviceName,
	PloytecDriverExternalMethod_GetDeviceManufacturer,
	PloytecDriverExternalMethod_GetPlaybackStats,
	PloytecDriverExternalMethod_SetCurrentUrbCount,
	PloytecDriverExternalMethod_GetCurrentUrbCount,
	PloytecDriverExternalMethod_SetCurrentInputFramesCount,
	PloytecDriverExternalMethod_GetCurrentInputFramesCount,
	PloytecDriverExternalMethod_SetCurrentOutputFramesCount,
	PloytecDriverExternalMethod_GetCurrentOutputFramesCount,
	PloytecDriverExternalMethod_RegisterForMIDINotification,
	PloytecDriverExternalMethod_SendMIDI,
};

#endif /* PloytecDriverKeys_h */
